test = {   'name': 'q1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> # Your encryption code is wrong;\n>>> msg = \'secret message\';\n>>> railfence(msg,4)=="SMEET EGCES ARS"\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # Your decryption code is wrong;\n>>> msg = \'secret message\';\n>>> railfence("SESEE RTESG CMA",4,False) == "seemseergacts"\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
